version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "seqre-py"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bqdh0ronq621"
s3_prefix = "seqre-py"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
