version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SeQRe-API"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2eyg41pq1x3u"
s3_prefix = "SeQRe-API"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
