AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SeQRe-API

  Sample SAM Template for SeQRe-API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: python3.8
    Environment:
      Variables:
        PRIMARY_KEY_TABLE: !Ref PrimaryKeyTable
        SESSION_KEY_TABLE: !Ref SessionKeyTable

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/hello_world/
      Handler: hello_world.lambda_handler
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello_world
            Method: get
  
  CreateAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create_account/
      Handler: create_account.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PrimaryKeyTable
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /createAccount
            Method: POST

  GetCAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_cauth/
      Handler: get_cauth.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PrimaryKeyTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionKeyTable
      Events:
        GetCAuth:
          Type: Api 
          Properties:
            Path: /getCAuth
            Method: POST

  AuthenticateSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/authenticate_session/
      Handler: authenticate_session.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionKeyTable
      Events:
        GetCAuth:
          Type: Api 
          Properties:
            Path: /authenticateSession
            Method: POST

  PrimaryKeyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id+alias
        Type: String

  SessionKeyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
