version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "seqre-py-v2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2eyg41pq1x3u"
s3_prefix = "seqre-py-v2"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
